### ISSUE TITLE
Put Docker image in DockerHub

### ISSUE THREAD

**Issue by himty** [berkeleyauv/robosub#12]
- Create a club Docker account
- Build the simulator Docker image
- Put it on DockerHub

I believe a version is currently on Jonathan's personal account, but it would be good to host on a club account

**Comment by AVSurfer123** [comment]
Dockerhub repo is `berkeleyauv:simulator`

**Comment by AVSurfer123** [comment]
Done here https://hub.docker.com/repository/docker/berkeleyauv/simulator. However, only the `xenial` version is there. A `melodic` version will also need to be built.
