### ISSUE TITLE
Implement keyboard/joystick teleop

### ISSUE THREAD

**Issue by himty** [berkeleyauv/robosub#19]
Implement [teleop_twist_keyboard](http://wiki.ros.org/teleop_twist_keyboard) ROS package

**Comment by caelinsutch** [comment]
Do after #53

**Comment by caelinsutch** [comment]
@AVSurfer123 What controller do we want to be able to use? I can setup for a xbox controller by default if that works. I'm creating a new file called `joy_handler` that takes in the `/joy` node and converts that to a `Twist` message. @Michael-Equi is this bad practice? Let me know what you think about it

**Comment by AVSurfer123** [comment]
For now just keyboard is needed. You can add xbox controller support too but I don't have one so I can't use it. And yea I'm not sure whether we need an intermediary /joy topic instead of having the node directly publish joystick commands to `/sub/cmd_vel`

**Comment by AVSurfer123** [comment]
actually we do need it so that we can programatically choose either joystick or auton control

**Comment by Michael-Equi** [comment]
There are existing packages that do all of this stuff for you such as https://index.ros.org/p/teleop_twist_joy/github-ros2-teleop_twist_joy/#foxy

**Comment by Michael-Equi** [comment]
and https://github.com/ros2/teleop_twist_keyboard

**Comment by caelinsutch** [comment]
@AVSurfer123 I'm probably just going to put the `teleop_twist_joy` package into the launch file w the velocity controller if that works.

**Comment by caelinsutch** [comment]
I know I've been lagging on this, other club work has been destroying me. I'm gonna integrate this today.

**Comment by AVSurfer123** [comment]
Closed in berkeleyauv/controls
