### ISSUE TITLE
Figure out if Gazebo can be run headless, and if images can be rendered

### ISSUE THREAD

**Issue by AVSurfer123** [berkeleyauv/robosub#35]
This would be good so that we could do some sort of integration testing with Travis/Gitlab, and also do testing without a GPU.
Some links that might help:
http://wiki.ros.org/simulator_gazebo/Tutorials/RunningSimulatorHeadless
https://answers.gazebosim.org//question/22030/run-gazebo-headless-on-aws-and-render-locally-with-the-gzclient/

**Comment by marcogelle** [comment]
So far, to launch gazebo without the GUI, changing the value to "false" in <arg name="gui" default="value"/> inside descriptions/vortex_descriptions/launch/robosub_world.launch (or whatever relevant launch file) works. It is found near the top of the file.
However, the windows for the camera inputs still pop up. I am currently looking for a way to fix this. I am also looking for an easier way to run Gazebo headless without changing code itself, such as command line options.

**Comment by marcogelle** [comment]
Update: when running using roslaunch, just add `gui:=false` to run Gazebo headless. Example:
`roslaunch vortex_descriptions robosub_world_sub.launch gui:=false`.
The camera windows still pop up, which I am working on now.

**Comment by marcogelle** [comment]
I verified that the images can be rendered through OpenCV with the script show_images.py, even with Gazebo running headless.
